"""Tests for the raw IBKR price-history ingest.

Every test points FINANCE_STORE at a temporary directory so nothing touches
the real ~/.finance. The fixtures under fixtures/ are synthetic: the symbols
TESTA, TESTB and TESTFX, the exchanges TESTX, TESTY and TESTFXX, contract ids
below 1000 and prices generated by the formula each fixture states in its
``_comment`` field. Nothing here resembles a real instrument or account.
"""

from __future__ import annotations

import copy
import io
import json
import os
import shutil
import sys
import tempfile
import unittest
from contextlib import redirect_stderr, redirect_stdout

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import ingest  # noqa: E402
import registry  # noqa: E402
import store  # noqa: E402

FIXTURES = os.path.join(os.path.dirname(os.path.abspath(__file__)), "fixtures")

DELAYED_FIXTURE = os.path.join(FIXTURES, "ibkr_history_daily_delayed.json")
LIVE_FIXTURE = os.path.join(FIXTURES, "ibkr_history_daily_live.json")
FX_FIXTURE = os.path.join(FIXTURES, "ibkr_history_fx.json")

#: Synthetic ISIN with a valid check digit; not issued to any real instrument.
ISIN_TESTA = "ZZ0000TESTA1"


def load_fixture(path):
    with open(path) as handle:
        return json.load(handle)


class IngestTestCase(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.mkdtemp(prefix="finance-ingest-test-")
        self._prev = os.environ.get("FINANCE_STORE")
        os.environ["FINANCE_STORE"] = self.tmp

    def tearDown(self):
        if self._prev is None:
            os.environ.pop("FINANCE_STORE", None)
        else:
            os.environ["FINANCE_STORE"] = self._prev
        shutil.rmtree(self.tmp, ignore_errors=True)

    def run_cli(self, argv):
        out = io.StringIO()
        err = io.StringIO()
        with redirect_stdout(out), redirect_stderr(err):
            code = ingest.main(argv)
        return code, out.getvalue(), err.getvalue()

    def write_raw(self, data, name="raw.json"):
        path = os.path.join(self.tmp, name)
        with open(path, "w") as handle:
            json.dump(data, handle)
        return path

    def store_files(self):
        base = os.path.join(self.tmp, "bars")
        found = []
        for directory, _, filenames in os.walk(base):
            for filename in filenames:
                found.append(os.path.join(directory, filename))
        return sorted(found)


class TestDelayedDaily(IngestTestCase):
    def test_sidecar_records_the_delay_and_the_venue(self):
        sidecar = ingest.ingest_ibkr_history(
            load_fixture(DELAYED_FIXTURE),
            symbol="TESTA",
            exchange="testx",
            currency="eur",
            contract_id=101,
        )
        self.assertEqual(sidecar["key"], "TESTX_TESTA")
        self.assertEqual(sidecar["source"], "ibkr")
        self.assertEqual(sidecar["interval"], "1d")
        self.assertEqual(sidecar["delayed_sec"], 900)
        self.assertEqual(sidecar["price_source"], "Last")
        self.assertEqual(sidecar["exchange"], "TESTX")
        self.assertEqual(sidecar["currency"], "EUR")
        self.assertEqual(sidecar["contract_id"], 101)
        self.assertEqual(sidecar["bar_count"], 12)
        self.assertEqual(sidecar["start"], "2026-08-03")
        self.assertEqual(sidecar["end"], "2026-08-14")
        self.assertIs(sidecar["adjusted"], False)

    def test_bars_round_trip_through_the_store(self):
        ingest.ingest_ibkr_history(
            load_fixture(DELAYED_FIXTURE),
            symbol="TESTA",
            exchange="TESTX",
            currency="EUR",
        )
        rows, meta = store.read_bars("ibkr", "TESTX_TESTA", "1d")
        self.assertEqual(len(rows), 12)
        self.assertEqual(rows[0]["date"], "2026-08-03")
        # close_i = 100 + i, open = close - 0.5, high = close + 1,
        # low = close - 1, volume = 1000 * (i + 1).
        self.assertEqual(rows[0]["close"], 100.0)
        self.assertEqual(rows[0]["open"], 99.5)
        self.assertEqual(rows[0]["high"], 101.0)
        self.assertEqual(rows[0]["low"], 99.0)
        self.assertEqual(rows[0]["volume"], 1000.0)
        self.assertEqual(rows[-1]["close"], 111.0)
        self.assertEqual(meta["bar_count"], 12)


class TestLiveDaily(IngestTestCase):
    def test_absent_delayed_key_means_zero(self):
        sidecar = ingest.ingest_ibkr_history(
            load_fixture(LIVE_FIXTURE),
            symbol="TESTB",
            exchange="TESTY",
            currency="USD",
        )
        self.assertEqual(sidecar["delayed_sec"], 0)

    def test_epoch_second_timestamps_are_accepted(self):
        raw = load_fixture(LIVE_FIXTURE)
        self.assertIsInstance(raw["time"][0], int)
        ingest.ingest_ibkr_history(
            raw, symbol="TESTB", exchange="TESTY", currency="USD"
        )
        rows, _ = store.read_bars("ibkr", "TESTY_TESTB", "1d")
        self.assertEqual([row["date"] for row in rows][:3],
                         ["2026-08-03", "2026-08-04", "2026-08-05"])
        self.assertEqual(rows[0]["close"], 200.0)


class TestFxSeries(IngestTestCase):
    def test_missing_volume_array_leaves_the_column_empty(self):
        sidecar = ingest.ingest_ibkr_history(
            load_fixture(FX_FIXTURE),
            symbol="TESTFX",
            exchange="TESTFXX",
            currency="USD",
        )
        self.assertEqual(sidecar["price_source"], "MidPoint")
        rows, _ = store.read_bars("ibkr", "TESTFXX_TESTFX", "1d")
        self.assertEqual(len(rows), 5)
        for row in rows:
            self.assertIsNone(row["volume"])

    def test_2115z_stamps_land_on_the_prior_local_calendar_day(self):
        # The fixture stamps each bar 21:15:00Z, the way IDEALPRO stamps FX
        # daily bars. store.session_date takes the UTC date, so a bar that is
        # already 00:15 the next day in Tallinn carries the prior calendar
        # day as its session date. That is the alignment returns.py relies on.
        ingest.ingest_ibkr_history(
            load_fixture(FX_FIXTURE),
            symbol="TESTFX",
            exchange="TESTFXX",
            currency="USD",
        )
        rows, _ = store.read_bars("ibkr", "TESTFXX_TESTFX", "1d")
        self.assertEqual(
            [row["date"] for row in rows],
            ["2026-08-03", "2026-08-04", "2026-08-05", "2026-08-06", "2026-08-07"],
        )


class TestIntervalFromChartStep(IngestTestCase):
    def test_weekly_step_without_an_explicit_interval(self):
        raw = load_fixture(DELAYED_FIXTURE)
        raw["chart_step"] = 604800
        sidecar = ingest.ingest_ibkr_history(
            raw, symbol="TESTA", exchange="TESTX", currency="EUR"
        )
        self.assertEqual(sidecar["interval"], "1w")

    def test_explicit_interval_wins_over_chart_step(self):
        raw = load_fixture(DELAYED_FIXTURE)
        raw["chart_step"] = 604800
        sidecar = ingest.ingest_ibkr_history(
            raw, symbol="TESTA", exchange="TESTX", currency="EUR", interval="1d"
        )
        self.assertEqual(sidecar["interval"], "1d")

    def test_unknown_step_without_an_interval_is_an_error(self):
        raw = load_fixture(DELAYED_FIXTURE)
        raw["chart_step"] = 12345
        path = self.write_raw(raw)
        code, _, err = self.run_cli(
            ["ibkr-history", path, "--symbol", "TESTA",
             "--exchange", "TESTX", "--currency", "EUR"]
        )
        self.assertEqual(code, 1)
        self.assertIn("12345", err)
        self.assertEqual(self.store_files(), [])

    def test_unknown_step_with_an_explicit_interval_is_fine(self):
        raw = load_fixture(DELAYED_FIXTURE)
        raw["chart_step"] = 12345
        sidecar = ingest.ingest_ibkr_history(
            raw, symbol="TESTA", exchange="TESTX", currency="EUR", interval="1d"
        )
        self.assertEqual(sidecar["interval"], "1d")


class TestValidation(IngestTestCase):
    def cli_failure(self, raw, extra=None):
        path = self.write_raw(raw)
        argv = ["ibkr-history", path, "--symbol", "TESTA",
                "--exchange", "TESTX", "--currency", "EUR"]
        code, out, err = self.run_cli(argv + (extra or []))
        self.assertEqual(code, 1, out)
        self.assertEqual(self.store_files(), [])
        return err

    def test_length_mismatch_writes_nothing(self):
        raw = load_fixture(DELAYED_FIXTURE)
        raw["high"] = raw["high"][:-1]
        err = self.cli_failure(raw)
        self.assertIn("high", err)

    def test_volume_length_mismatch_writes_nothing(self):
        raw = load_fixture(DELAYED_FIXTURE)
        raw["volume"] = raw["volume"][:-2]
        err = self.cli_failure(raw)
        self.assertIn("volume", err)

    def test_missing_close_array(self):
        raw = load_fixture(DELAYED_FIXTURE)
        del raw["close"]
        err = self.cli_failure(raw)
        self.assertIn("close", err)

    def test_empty_series(self):
        raw = load_fixture(DELAYED_FIXTURE)
        for field in ("time", "open", "high", "low", "close", "volume"):
            raw[field] = []
        err = self.cli_failure(raw)
        self.assertIn("empty", err.lower())

    def test_unparseable_time(self):
        raw = load_fixture(DELAYED_FIXTURE)
        raw["time"][3] = "not-a-timestamp"
        err = self.cli_failure(raw)
        self.assertIn("not-a-timestamp", err)

    def test_non_numeric_price(self):
        raw = load_fixture(DELAYED_FIXTURE)
        raw["close"][2] = "n/a"
        err = self.cli_failure(raw)
        self.assertIn("close", err)

    def test_null_price(self):
        raw = load_fixture(DELAYED_FIXTURE)
        raw["low"][0] = None
        err = self.cli_failure(raw)
        self.assertIn("low", err)

    def test_arrays_must_be_lists(self):
        raw = load_fixture(DELAYED_FIXTURE)
        raw["open"] = 42
        err = self.cli_failure(raw)
        self.assertIn("open", err)

    def test_two_timestamps_on_the_same_utc_date_write_nothing(self):
        raw = load_fixture(DELAYED_FIXTURE)
        # both fall on 2026-08-24 UTC at the 1d session-date resolution,
        # even though they are distinct instants.
        raw["time"] = raw["time"][:2]
        raw["time"][0] = "2026-08-24T07:00:00Z"
        raw["time"][1] = "2026-08-24T15:00:00Z"
        for field in ("open", "high", "low", "close", "volume"):
            raw[field] = raw[field][:2]
        err = self.cli_failure(raw)
        self.assertIn("2026-08-24", err)

    def test_unreadable_raw_file(self):
        path = os.path.join(self.tmp, "missing.json")
        code, _, err = self.run_cli(
            ["ibkr-history", path, "--symbol", "TESTA",
             "--exchange", "TESTX", "--currency", "EUR"]
        )
        self.assertEqual(code, 1)
        self.assertIn("missing.json", err)

    def test_malformed_raw_file(self):
        path = os.path.join(self.tmp, "bad.json")
        with open(path, "w") as handle:
            handle.write("{not json")
        code, _, err = self.run_cli(
            ["ibkr-history", path, "--symbol", "TESTA",
             "--exchange", "TESTX", "--currency", "EUR"]
        )
        self.assertEqual(code, 1)
        self.assertIn("bad.json", err)


class TestRegistryLink(IngestTestCase):
    def test_registry_hit_fills_the_isin(self):
        registry.add(
            ISIN_TESTA,
            name="Test Fund A",
            class_="etf",
            ibkr=[{"contract_id": 101, "exchange": "TESTX",
                   "symbol": "TESTA", "currency": "EUR"}],
        )
        sidecar = ingest.ingest_ibkr_history(
            load_fixture(DELAYED_FIXTURE),
            symbol="TESTA",
            exchange="TESTX",
            currency="EUR",
        )
        self.assertEqual(sidecar["isin"], ISIN_TESTA)

    def test_registry_miss_leaves_the_isin_null(self):
        sidecar = ingest.ingest_ibkr_history(
            load_fixture(DELAYED_FIXTURE),
            symbol="TESTA",
            exchange="TESTX",
            currency="EUR",
        )
        self.assertIsNone(sidecar["isin"])


class TestAdjustedFlag(IngestTestCase):
    def test_default_is_false(self):
        code, out, _ = self.run_cli(
            ["ibkr-history", DELAYED_FIXTURE, "--symbol", "TESTA",
             "--exchange", "TESTX", "--currency", "EUR", "--json"]
        )
        self.assertEqual(code, 0)
        self.assertIs(json.loads(out)["adjusted"], False)

    def test_true_and_false_and_null(self):
        for text, expected in (("true", True), ("false", False), ("null", None)):
            code, out, err = self.run_cli(
                ["ibkr-history", DELAYED_FIXTURE, "--symbol", "TESTA",
                 "--exchange", "TESTX", "--currency", "EUR",
                 "--adjusted", text, "--json"]
            )
            self.assertEqual(code, 0, err)
            self.assertIs(json.loads(out)["adjusted"], expected)


class TestCli(IngestTestCase):
    def test_human_output_names_the_key_and_bar_count(self):
        code, out, err = self.run_cli(
            ["ibkr-history", DELAYED_FIXTURE, "--symbol", "TESTA",
             "--exchange", "TESTX", "--currency", "EUR", "--contract-id", "101"]
        )
        self.assertEqual(code, 0, err)
        self.assertIn("TESTX_TESTA", out)
        self.assertIn("12", out)
        self.assertIn("900", out)
        self.assertIn("Last", out)
        self.assertIn("2026-08-03", out)
        self.assertIn("2026-08-14", out)

    def test_json_output_parses_and_matches_the_sidecar_on_disk(self):
        code, out, err = self.run_cli(
            ["ibkr-history", FX_FIXTURE, "--symbol", "TESTFX",
             "--exchange", "TESTFXX", "--currency", "USD", "--json"]
        )
        self.assertEqual(code, 0, err)
        printed = json.loads(out)
        self.assertEqual(printed["key"], "TESTFXX_TESTFX")
        self.assertEqual(
            printed, store.read_meta("ibkr", "TESTFXX_TESTFX", "1d")
        )

    def test_no_subcommand_prints_help_and_fails(self):
        code, _, err = self.run_cli([])
        self.assertEqual(code, 1)
        self.assertIn("ibkr-history", err)

    def test_fixture_input_is_not_mutated(self):
        raw = load_fixture(DELAYED_FIXTURE)
        before = copy.deepcopy(raw)
        ingest.ingest_ibkr_history(
            raw, symbol="TESTA", exchange="TESTX", currency="EUR"
        )
        self.assertEqual(raw, before)


class TestFixtures(unittest.TestCase):
    """The fixtures themselves must stay synthetic and self-describing."""

    def test_every_fixture_states_its_price_formula(self):
        for path in (DELAYED_FIXTURE, LIVE_FIXTURE, FX_FIXTURE):
            data = load_fixture(path)
            self.assertIn("_comment", data, path)
            self.assertIn("close_i", data["_comment"], path)

    def test_shapes_match_the_documented_variants(self):
        delayed = load_fixture(DELAYED_FIXTURE)
        self.assertEqual(delayed["delayed"], 900)
        self.assertEqual(len(delayed["close"]), 12)

        live = load_fixture(LIVE_FIXTURE)
        self.assertNotIn("delayed", live)
        self.assertEqual(len(live["close"]), 12)

        fx = load_fixture(FX_FIXTURE)
        self.assertNotIn("volume", fx)
        self.assertEqual(fx["source"], "MidPoint")
        self.assertEqual(len(fx["close"]), 5)


class TestIntervalArgumentIsConstrained(IngestTestCase):
    """--interval is a closed set, so it cannot become a chosen filename."""

    def setUp(self):
        super().setUp()
        self.sandbox = self.tmp
        self.store_root = os.path.join(self.sandbox, "store")
        os.makedirs(self.store_root)
        os.environ["FINANCE_STORE"] = self.store_root

    def test_traversing_interval_is_refused_and_writes_nothing(self):
        raw = self.write_raw(load_fixture(DELAYED_FIXTURE))
        argv = [
            "ibkr-history",
            raw,
            "--symbol",
            "TESTA",
            "--exchange",
            "TESTX",
            "--currency",
            "EUR",
            "--interval",
            "1d/../x",
        ]
        try:
            code, _, _ = self.run_cli(argv)
        except SystemExit as exc:
            code = exc.code
        self.assertIn(code, (1, 2))
        self.assertEqual(sorted(os.listdir(self.store_root)), [])
        self.assertEqual(sorted(os.listdir(self.sandbox)), ["raw.json", "store"])

    def test_known_intervals_are_still_accepted(self):
        raw = self.write_raw(load_fixture(DELAYED_FIXTURE))
        code, _, err = self.run_cli(
            [
                "ibkr-history",
                raw,
                "--symbol",
                "TESTA",
                "--exchange",
                "TESTX",
                "--currency",
                "EUR",
                "--interval",
                "1d",
            ]
        )
        self.assertEqual(code, 0, err)


if __name__ == "__main__":
    unittest.main()
